# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-01-26 10:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20220125_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('c_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
